easy_admin:
    entities:
        # List the entity class name you want to manage
        AppRole:
            class: App\Entity\AppRole
            help: 'Voici la liste des différents Rôles dans le site'
            label: Roles
            list:
                fields: 
                    - { property: 'id', label: 'Id'} 
                    - { property: 'name', label: 'Nom'} 
                    - { property: 'users', label: 'Membres'} 
                    - { property: 'code', label: 'Code'} 
            show: 
                title: 'Un Rôle'
                help: null
                fields:
                    - { property: 'id', label: 'Id'} 
                    - { property: 'name', label: 'Nom'} 
                    - { property: 'users', label: 'Membres'} 
                    - { property: 'code', label: 'Code'} 
        Category:
            class: App\Entity\Category
            help: 'Voici la liste des Catégories et Sous-Catégories associées' 
            label: Catégories
            list:
                fields: 
                    - { property: 'id', label: 'Id'} 
                    - { property: 'name', label: 'Nom'}
                    - { property: 'quizzs', label: 'Quizzes'} 
                    - { property: 'parent', label: 'Catégorie Principale'} 
                    - { property: 'children', label: 'Sous-catégorie'} 
            show: 
                title: 'Une Catégorie / Sous-Catégorie'
                help: null
                fields:
                    - { property: 'id', label: 'Id'} 
                    - { property: 'name', label: 'Nom'} 
                    - { property: 'quizzs', label: 'Quizzes'} 
                    - { property: 'parent', label: 'Catégorie Principale'} 
                    - { property: 'children', label: 'Sous-catégorie'}
        Crew:
            class: App\Entity\Crew
            help: 'Voici la liste des Teams'
            label: Team
            list: 
                fields: 
                    - { property: 'id', label: 'Id'}
                    - { property: 'name', label: 'Nom'}
                    - { property: 'avatar', type: 'image', base_path: '/img/'}
                    - { property: 'members', label: 'Membres'}
                    - { property: 'quizzs', label: 'Quizzes'} 
                    - { property: 'createdAt', label: 'Crée le :'}
            show: 
                title: 'Une Team'
                help: null
                fields:
                    - { property: 'id', label: 'Id'}
                    - { property: 'name', label: 'Nom'}
                    - { property: 'avatar', type: 'image', base_path: '/img/'}
                    - { property: 'members', label: 'Membres'}
                    - { property: 'quizzs', label: 'Quizzes'} 
                    - { property: 'createdAt', label: 'Crée le :'}
        #IsLike:
        #    class: App\Entity\IsLike
        #Single id is not allowed on composite primary key in entity App\Entity\IsLike
        Level:
            class: App\Entity\Level
            help: 'Voici la liste des Niveaux de difficulté de jeu'
            label: Niveaux
            list:
                fields: ['id', { property: 'name', label: 'Nom'}, { property: 'quizzs', label: 'Quizzes'}, 'questions']
        Question:
            class: App\Entity\Question
            help: 'Voici la liste de toutes les Questions'
            label: Questions
            list: 
                fields: ['id', { property: 'body', label: 'Intitulé de la Question'}, { property: 'prop1', label : 'Réponse 1'}, { property: 'prop2', label : 'Réponse 2'}, { property: 'prop3', label : 'Réponse 3'}, { property: 'prop4', label : 'Réponse 4'}, 'anecdote', { property: 'source', type: 'url'} ]
        Quizz:
            class: App\Entity\Quizz
            help: 'Voici la liste de tous les Quizzes'
            label: Quizzes
            list:
                fields: ['id', { property: 'title', label: 'Titre'}, { property: 'category', label: 'Catégorie'}, 'questions', { property: 'IsPrivate', label: 'Privée'}, { property : 'isLikes', label: 'Likes'}, { property: 'statistics', label: 'Résultats'}]
        RoleCrew:
            class: App\Entity\RoleCrew
            help: 'Voici la liste des Rôles dans la Team'
            label: Roles dans la Team
            list:
                fields: ['id', {property: 'name', label: 'Nom'}, {property: 'userCrews', label: 'Membre Teams'}, 'code']
        Statistic: 
            class: App\Entity\Statistic
            help: 'Voici la liste des Résultats (statistiques)'
            label: Résultats
            list: 
                fields: ['id', 'quizz', {property: 'user', label: 'Membre'}, 'result', { property: 'createdAt', label: 'Création le'}]
        User:
            class: App\Entity\User
            help: 'Voici la liste de tous les Utlisateurs inscrits'
            label: Membres
            list: 
                fields: ['id', { property: 'userName', label: 'Nom'}, { property: 'email', type: 'email'}, { property: 'avatar', type: image, base_path: '/img/'}, 'presentation', { property: 'createdAt', label: 'Création le'}, { property: 'isActif', label: 'Activer'}]
        
        #UserCrew:
        #    class: App\Entity\UserCrew
        # Single id is not allowed on composite primary key in entity App\Entity\UserCrew

    site_name: '<img src="" /><u style="font-size: 120%;">Les VallesBaques</u>'
    design:
        brand_color: '#002547'
        # Ici on peut ajouter un CSS + JS custom
        assets:
            css:
                - build/appAdmin.css
        
        menu:
            - {entity: 'AppRole', icon: 'check'}
            - {entity: 'RoleCrew', icon: 'check'}
            - {entity: 'User', icon: 'user'}
            - {entity: 'Crew', icon: 'users'}
            - {entity: 'Statistic', icon: 'bullhorn'}
            - {entity: 'Quizz', icon: 'question'}
            - {entity: 'Question', icon: 'question'}
            - {entity: 'Category', icon: 'tags'}
            - {entity: 'Level', icon: 'signal'}
            # Permet le retour vers la l'Accueil du site
            - {label: 'Accueil du site', route: 'home', icon: 'home' }
            - {label: 'Page inscription', route: 'security_signup', icon: 'sign-in' }
            - {label: 'Page connexion', route: 'security_login', icon: 'sign-in' }

    list:
        title: 'Liste %%entity_label%%'
        max_results: 20
        
        actions: 
            - { name: 'show', icon: 'eye', label: '', title: 'Show'}
            - { name: 'edit', icon: 'edit', label: '', title: 'Edit'}
            - { name: 'delete', icon: 'trash', label: '', title: 'Delete'}

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

framework:
    translator: { fallbacks: [ "fr" ] }