easy_admin:
    entities:
        # List the entity class name you want to manage
        AppRole:
            class: App\Entity\AppRole
            label: Roles
            list:
                fields: ['id', { property: 'name', label: 'Nom'}, { property: 'users', label: 'Membres'}, 'code']
        Category:
            class: App\Entity\Category 
            label: Catégories
        Crew:
            class: App\Entity\Crew
            label: Team
            list: 
                fields: ['id', { property: 'name', label: 'Nom'}, 'avatar', { property: 'members', label: 'Membres'}, 'quizzs', { property: 'createdAt', label: 'Crée le :'}]
        #IsLike:
        #    class: App\Entity\IsLike
        #Single id is not allowed on composite primary key in entity App\Entity\IsLike
        Level:
            class: App\Entity\Level
            label: Niveaux
        Question:
            class: App\Entity\Question
            label: Questions
        Quizz:
            class: App\Entity\Quizz
            label: Quizzes
        RoleCrew:
            class: App\Entity\RoleCrew
            label: Roles dans la Team
            list:
                fields: ['id', {property: 'name', label: 'Nom'}, {property: 'userCrews', label: 'Membre Teams'}, 'code']
        Statistic: 
            class: App\Entity\Statistic
            label: Résultats
            list: 
                fields: ['id', 'quizz', {property: 'user', label: 'Membre'}, 'result', 'createdAt']
        User:
            class: App\Entity\User
            label: Membres
            list: 
                fields: ['id', { property: 'userName', label: 'Nom'}, 'email', 'avatar', 'presentation', { property: 'createdAt', label: 'Crée le :'}, 'isActif']
            
        #UserCrew:
        #    class: App\Entity\UserCrew
        # Single id is not allowed on composite primary key in entity App\Entity\UserCrew

    site_name: '<img src="" /><span style="font-size: 120%;">Les VallesBaques</span>'
    design:
        brand_color: '#002547'
        # Ici on peut ajouter un CSS + JS custom
        #assets:
        #    css:
        
        menu:
            - {entity: 'User', icon: 'user'}
            - {entity: 'Statistic', icon: 'signal'}
            - {entity: 'Crew', icon: 'users'}
            - {entity: 'AppRole', icon: 'check'}
            - {entity: 'RoleCrew', icon: 'users'}
            - {entity: 'Quizz', icon: 'question'}
            - {entity: 'Question', icon: 'question'}
            - {entity: 'Category', icon: 'tags'}
            - {entity: 'Level', icon: 'play'}
            - {label: 'Accueil', route: 'home', icon: 'file' }
            - {label: 'Inscription', route: 'security_signup', icon: 'file' }
            - {label: 'Connexion', route: 'security_login', icon: 'file' }
    
    list:
        title: 'Liste : %%entity_label%%'
        max_results: 20

framework:
    translator: { fallbacks: [ "fr" ] }